name: Update GitHub Blog

on:
  workflow_dispatch:          # manual trigger from the Actions tab
  schedule:
    - cron: '0 2 * * *'      # optional nightly run (02:00 UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------------------------------
      # 1️⃣ Checkout the repository (no credentials yet)
      # --------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # we’ll push with our own token

      # --------------------------------------------------------------
      # 2️⃣ Set up Node.js (cache only if a lock file exists)
      # --------------------------------------------------------------
      - name: Set up Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Enable npm cache only when a lock file is present
          cache: ${{ (hashFiles('package-lock.json') != '' || hashFiles('yarn.lock') != '' ) && 'npm' || '' }}

      # --------------------------------------------------------------
      # 3️⃣ Install dependencies (npm or Yarn) – works both ways
      # --------------------------------------------------------------
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "🔧 npm lock detected – installing with npm ci"
            npm ci                         # respects package-lock.json
          elif [ -f yarn.lock ]; then
            echo "🔧 Yarn lock detected – installing with Yarn"
            yarn install --frozen-lockfile
          else
            echo "⚠️ No lock file – installing required packages only"
            npm install prettier --no-package-lock
          fi

      # --------------------------------------------------------------
      # 4️⃣ Run the script that updates the HTML page
      # --------------------------------------------------------------
      - name: Generate blog cards
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # optional, only if script calls the GitHub API
          GITHUB_USER: exo-exe                    # replace with your user/org
        run: node ./scripts/update-github-blog.js

      # --------------------------------------------------------------
      # 5️⃣ Commit and push the changes (authenticated)
      # --------------------------------------------------------------
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure the bot identity (the name/email are optional)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage only tracked files that changed
          git add -u

          # If nothing changed, stop here
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
            exit 0
          fi

          # Commit with a clear message
          git commit -m "🤖 Auto‑update GitHub blog cards"

          # Push using the built‑in token – no interactive password prompt
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" \
            HEAD:${{ github.ref_name }}
