name: Update GitHub Blog

on:
  workflow_dispatch:          # manual trigger from the Actions tab
  schedule:
    - cron: '0 2 * * *'      # optional nightly run (02:00 UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # --------------------------------------------------------------
      # 1️⃣ Checkout the repository (no credentials yet)
      # --------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # we’ll push with our own token

      # --------------------------------------------------------------
      # 2️⃣ Set up Node.js (cache only if a lock file exists)
      # --------------------------------------------------------------
      - name: Set up Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Enable npm cache only when a lock file is present
          cache: ${{ (hashFiles('package-lock.json') != '' || hashFiles('yarn.lock') != '' ) && 'npm' || '' }}

      # --------------------------------------------------------------
      # 3️⃣ Install dependencies (npm or Yarn) – works both ways
      # --------------------------------------------------------------
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "🔧 npm lock detected – installing with npm ci"
            npm ci                         # respects package-lock.json
          elif [ -f yarn.lock ]; then
            echo "🔧 Yarn lock detected – installing with Yarn"
            yarn install --frozen-lockfile
          else
            echo "⚠️ No lock file – installing required packages only"
            npm install prettier --no-package-lock
          fi

      # --------------------------------------------------------------
      # 4️⃣ Run the script that updates the H
