name: Update GitHub Blog

on:
  workflow_dispatch:          
  schedule:
    - cron: '0 2 * * *'      

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write          

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false   


      - name: Set up Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ${{ (hashFiles('package-lock.json') != '' || hashFiles('yarn.lock') != '' ) && 'npm' || '' }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "🔧 npm lock detected – installing with npm ci"
            npm ci                     # respects package-lock.json
          elif [ -f yarn.lock ]; then
            echo "🔧 Yarn lock detected – installing with Yarn"
            yarn install --frozen-lockfile
          else
            echo "⚠️ No lock file – installing required packages only"
            npm install prettier --no-package-lock
          fi


      - name: Generate blog cards
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          GITHUB_USER: exo-exe                    
        run: node ./scripts/update-github-blog.js


      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: |
          # Configure the bot identity (optional, just for nice commit metadata)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage only tracked files that changed
          git add -u

          # If nothing changed, exit cleanly
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
            exit 0
          fi

          # Commit
          git commit -m "🤖 Auto‑update GitHub blog cards"

          # Push using the token embedded in the URL.
          # ${GITHUB_ACTOR} = the user that triggered the workflow (usually the bot)
          # ${GITHUB_TOKEN} = the secret that grants write access for this run
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" \
            HEAD:${{ github.ref_name }}
